### ISSUE TITLE
No sync in Edge Windows Creator Update: SCRIPT65535: Invalid calling object

### ISSUE THREAD

**Issue by wassx** [networked-aframe/networked-aframe#98]
Hi!
I tried to connect to my server with an edge browser but there occurs an error in the console.
**SCRIPT65535: Invalid calling object networked-aframe.min.js (2,3147)**

Chrome and safari work as expected.
Any ideas please?

**Comment by wassx** [comment]
Ok, I found on the page of WebRtc: no edge supported. 😕

**Comment by wmurphyrd** [comment]
Looks like Edge WebRTC is available in preview builds as of a couple weeks ago: https://blogs.windows.com/msedgedev/2017/01/31/introducing-webrtc-microsoft-edge/#Hlcah5SRWeiITzeV.97

Have you tried it?

**Comment by wassx** [comment]
Ah thank you, I'll give it a try!

**Comment by robertlong** [comment]
There's still no support for DataChannels in Edge 🙁 
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/?filter=f3f0000bf&q=rtc

**Comment by wmurphyrd** [comment]
Just confirmed successful networking in WindowsMR on Edge using `wsEasyRTC` adapter

**Comment by wmurphyrd** [comment]
Note that the invalid calling object error traces back to https://github.com/networked-aframe/networked-aframe/blob/master/src/NafLogger.js#L24

Getting it to load in Edge requires that `networked-scene.debug` is false and that you avoid any other conditions that would invoke the NafLogger

**Comment by wmurphyrd** [comment]
So this may be a bug in Edge which has a fix in preview right now: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14495220/

**Comment by wmurphyrd** [comment]
The original issue, `SCRIPT65535: Invalid calling object`, is now fixed in the latest version of Edge (windows 10 v1803, build 17134.81), so this issue can probably be closed. Although we may still want an open issue to track full Edge compatibility. 

With that latest version, I get some partial support in Edge with the `EasyRTC` adapter now. Audio can stream between two Edge tabs on the same machine (but not to other browsers or even Edge on another machine), and other avatars sometimes sync into the Edge instance but not from Edge outwards.

**Comment by 3DataWill** [comment]
With a new beta from EasyRTC last week, voice and video conference with Edge worked for me in [their demo](https://easyrtc.sylaps.net/demos/demo_audio_video_simple.html), streaming between desktop Edge and Android Firefox.

Edge still doesn't have DataChannels, but perhaps the wseasyrtc adapter could be extended with audio support.

**Comment by vincentfretin** [comment]
Edge is now using Chromium. Closing.
